# Generated by Django 2.2.5 on 2019-09-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('beam', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
