# Generated by Django 2.2.5 on 2019-09-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sail',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
