# Generated by Django 2.2.5 on 2019-09-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190911_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='sails',
            field=models.ManyToManyField(to='main_app.Sail'),
        ),
    ]
